### ISSUE TITLE
Is it possible to simulate an IOException?

### ISSUE THREAD

**Issue by laedit** [tathamoddie/System.IO.Abstractions#103]
Like when a file is locked by another process for example.
It would be great for testing.

Thanks.

**Comment by tathamoddie** [comment]
This is what a library like NSubstitute is for.
The `System.IO.Abstractions.TestingHelpers` package is for when you want a quick, mostly-like-a-real-filesystem, mock.

**Comment by laedit** [comment]
Sorry, I haven't think of that.
Thank a lot for the quick answer and sorry again for the silly question.
