### ISSUE TITLE
Path.Combine() should take more than 2 aguments

### ISSUE THREAD

**Issue by ormico** [tathamoddie/System.IO.Abstractions#108]
Looks like Path.Combine(string path1, string path2) is implemented but not Path.Combine(params string[] paths)

**Comment by tathamoddie** [comment]
@ormico If you need it, can you send a pull request?

**Comment by ormico** [comment]
I put it on my todo list. I’ll send one over if I have a chance. Shouldn’t be too hard to implement.

**Comment by manne** [comment]
a quick reminder of what should be implemented.
https://msdn.microsoft.com/en-us/library/vstudio/ff652744(v=vs.100).aspx in section **System.IO Namespace**
I will make new issues to keep track of the missing methods.

**Comment by srasch** [comment]
I have implemented this in #111

**Comment by tathamoddie** [comment]
Merged.
