### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by bretthysuik** [tathamoddie/System.IO.Abstractions#123]
It would be very helpful if you could maintain a wiki page or document with the release notes for each version. I'm still on 1.4.0.x but I have no idea if 2.0.0.x has backwards incompatible changes (I assume it does since you bumped the major version). This is preventing me from upgrading to the latest version.

If 2.0.0.x *is* backwards incompatible, what are the breaking changes?

**Comment by manne** [comment]
The import change regarding to backward compatibility is the .NET version 4.0 (see 94a9fbcbe67c86b187c6d19de36d20482203602d). Before it is .NET version 3.5.

**Comment by tathamoddie** [comment]
Now published at https://github.com/tathamoddie/System.IO.Abstractions/releases/tag/v2.0.0.98

**Comment by bretthysuik** [comment]
@tathamoddie: Much appreciated. Thanks.
