### ISSUE TITLE
Directory.Move fails when a directory with different case already exists

### ISSUE THREAD

**Issue by borismod** [tathamoddie/System.IO.Abstractions#134]
Here is a unit test that reproduces the issue. 

`
        [Test]
        public void Move_DirectoryExistsWithDifferentCase_DirectorySuccessfullyMoved()
        {
            // Arrange
            var fileSystem = new MockFileSystem();
            fileSystem.AddDirectory(@"\\builds\Builds\Suites\6.2.3.309 [6.2.3 135907]\TestShellHotFix\Data"); // HotFix with capital F
            fileSystem.AddFile(     @"\\builds\Builds\Suites\6.2.3.309 [6.2.3 135907]\TestShellHotfix\Data\Content\DriverBuilder\ActiproSoftware.Navigation.Wpf.dll", new MockFileData("abc"));

            // Act
            fileSystem.Directory.Move(@"\\builds\Builds\Suites\6.2.3.309 [6.2.3 135907]\TestShellHotfix", // HotFix with lower f
                    @"\\builds\Builds\Suites\6.2.3.309 [6.2.3 135907]\Hotfix1 for CloudShell 6.2.3 GA [6.2.3.187]");

            // Assert
            Assert.IsTrue(
                fileSystem.File.Exists(@"\\builds\Builds\Suites\6.2.3.309 [6.2.3 135907]\Hotfix1 for CloudShell 6.2.3 GA [6.2.3.187]\Data\Content\DriverBuilder\ActiproSoftware.Navigation.Wpf.dll"));
        }

`

**Comment by ericnewton76** [comment]
Can we get a unit test that doesnt have so much specificity?  The paths you
have there are very specific, since you're testing for case, just create a
unit test where the directory name is C:\CaseSensitiveTest (for example).

**Comment by borismod** [comment]
@ericnewton76 Test was changed to be less specific. Can you review and accept the PR?
Thanks!

**Comment by tathamoddie** [comment]
Fixed by #135
