### ISSUE TITLE
Wrong behaviour in Directory.EnumerateFileSystemInfos

### ISSUE THREAD

**Issue by SebastianRoether** [tathamoddie/System.IO.Abstractions#136]
`GetFileSystemInfos("*", SearchOption.AllDirectories)` includes files while `EnumerateFileSystemInfos("*", SearchOption.AllDirectories)` does not.

They should only differ in eager/lazy loading of files which is not relevant for mocking (see https://msdn.microsoft.com/de-de/library/dd383689(v=vs.110).aspx)

**Comment by martindevans** [comment]
This should be fixed with [my PR](https://github.com/tathamoddie/System.IO.Abstractions/pull/143)
