### ISSUE TITLE
CI Build not working

### ISSUE THREAD

**Issue by manne** [tathamoddie/System.IO.Abstractions#163]
Hey @tathamoddie,

is the ci build still working?
The address was once [http://teamcity.tath.am/project.html?projectId=SystemIoAbstractions&tab=projectOverview](http://teamcity.tath.am/project.html?projectId=SystemIoAbstractions&tab=projectOverview). But i get an error 
`teamcity.tath.am’s DNS address could not be found.`

Therefore new nuget packages do not get deployed, too.

**Comment by tathamoddie** [comment]
It's now up and running again with AppVeyor.
