### ISSUE TITLE
Copying/Moving/Creating Files into pre-existing directories does not respect directory capitalization

### ISSUE THREAD

**Issue by AlexanderPruss** [tathamoddie/System.IO.Abstractions#190]
1. Create a Directory "C:\foo"
2. Create a file "C:\totallyNotVirus.exe"
3. Move the file to "C:\FOO\totallyNotVirus.exe"

Result: The file is in the MockFileSystem as "C:\FOO\totallyNotVirus.exe", not as "C:\foo\totallyNotVirus.exe".

**Comment by AlexanderPruss** [comment]
Here's a PR for this: https://github.com/tathamoddie/System.IO.Abstractions/pull/191

**Comment by nguyendangdung** [comment]
This because MockFileSystem dont think "C:\foo" is a directory. try "C:\foo\" instead

**Comment by AlexanderPruss** [comment]
MockFileSystem may not think so, but MSCorlib's FileSystem does.

**Comment by tathamoddie** [comment]
Fixed via #191
