### ISSUE TITLE
Has anybody tried a fresh clone of the project?

### ISSUE THREAD

**Issue by ericnewton76** [tathamoddie/System.IO.Abstractions#205]
Things aint working.  Nuget packages config have conflicting versions between root/packages/packages.config and TestHelpers.Test/packages.config and the nuget restore on build isn't working.

Trying to build a clean pull request dealing with issue #202 but I cant code coverage and test locally atm

**Comment by ericnewton76** [comment]
had to run nuget via command line:

in the TestHelpers.Tests directory, run ```nuget install -outputdirectory ..\packages```

**Comment by tathamoddie** [comment]
Should be sorted as of db4da83a857aa25e5ba895a2f69a802ed0798a12
