### ISSUE TITLE
MockFileSystem.Directory.CreateDirectory throws IoException when directory exists and argument has trailing slash

### ISSUE THREAD

**Issue by cmeeren** [tathamoddie/System.IO.Abstractions#210]
`MockFileSystem.Directory.CreateDirectory` throws an `IoException` if the directory already exists *and* the argument to `CreateDirectory()` contains a trailing slash.

The following works correctly:

````c#
var fs = new MockFileSystem();
fs.AddDirectory(@"C:\test\"); // Trailing slash here doesn't matter
fs.Directory.CreateDirectory(@"C:\test"); // No trailing slash works correctly
````

The following throws an `IOException`:

````c#
var fs = new MockFileSystem();
fs.AddDirectory(@"C:\test\"); // Trailing slash here doesn't matter
fs.Directory.CreateDirectory(@"C:\test\"); // Trailing slash here causes error
````

````
System.IO.IOException : Cannot create "C:\test\" because a file or directory with the same name already exists.
   at System.IO.Abstractions.TestingHelpers.MockDirectory.CreateDirectory(String path, DirectorySecurity directorySecurity)
   at System.IO.Abstractions.TestingHelpers.MockDirectory.CreateDirectory(String path)
````

The correct behaviour is silently ignoring existing directories, like `System.Io.Directory.CreateDirectory()` does (documented behavior).

**Comment by tathamoddie** [comment]
Thanks for reporting! Can you share a pull request that fixes this?

**Comment by cmeeren** [comment]
Done. Added tests for the bug as well as for checking that return value is not null, as per [MSDN documentation](https://msdn.microsoft.com/en-us/library/dd383460%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396):

> Return Value
> Type: System.IO.DirectoryInfo
> 
> An object that represents the directory at the specified path. This object is returned regardless of whether a directory at the specified path already exists.
