### ISSUE TITLE
Should MockFileSystem.AllFiles be locking "file" instead of "files"?

### ISSUE THREAD

**Issue by cmeeren** [tathamoddie/System.IO.Abstractions#212]
I came across this line: https://github.com/tathamoddie/System.IO.Abstractions/blob/master/TestingHelpers/MockFileSystem.cs#L200

I guess this should be `files` instead of `file`, as with the other similar properties.

**Comment by marcomeyer** [comment]
I agree. Created a PR #268

**Comment by tathamoddie** [comment]
Thanks!

**Comment by tathamoddie** [comment]
Should be on NuGet as 2.1.0.178 in a couple of minutes.
