### ISSUE TITLE
MockDirectoryInfo.ToString() should return directory name.

### ISSUE THREAD

**Issue by limdaepl** [tathamoddie/System.IO.Abstractions#215]
I came across a weird exception message:

> Could not find a part of the path 'System.IO.Abstractions.TestingHelpers.MockDirectoryInfo'.
    at System.IO.Abstractions.TestingHelpers.MockFile.VerifyDirectoryExists(String path)
    [...]

This is because the exception message implicitly uses `MockDirectoryInfo.ToString()` which isn't overriden and defaults to the type name. `System.IO.DirectoryInfo.ToString()` returns the directory name.

Minimal example:

```
const string path = "C:\\Users";

var realDirectory = new DirectoryInfo(path);
var mockDirectory = new MockDirectoryInfo(new MockFileSystem(), path);

Debug.Assert(realDirectory.ToString() == mockDirectory.ToString()); // fail

```

**Comment by tathamoddie** [comment]
Thanks for the report! Do you think you could submit a small pull request which adds a test and fix for this?

**Comment by limdaepl** [comment]
I haven't done this before but I'll give it a try.

**Comment by limdaepl** [comment]
I think that's it. Was this the correct procedure?
