### ISSUE TITLE
Directory.CreateDirectory should not throw Exception

### ISSUE THREAD

**Issue by brianestey** [tathamoddie/System.IO.Abstractions#218]
From the docs:
https://msdn.microsoft.com/en-us/library/54a0at6s(v=vs.110).aspx

The remarks say:
"Any and all directories specified in path are created, unless they already exist or unless some part of path is invalid. **_If the directory already exists, this method does not create a new directory, but it returns a DirectoryInfo object for the existing directory._**"

**Comment by tathamoddie** [comment]
Thanks for reporting! Are you able to send through a PR for this?

**Comment by brianestey** [comment]
Never done one before but what better time to learn, right? :)

**Comment by tathamoddie** [comment]
No problems; happy to help. Are you familiar with Git generally (`clone`, `commit`, `push`)?

**Comment by rdehuyss** [comment]
This is already fixed in PR https://github.com/tathamoddie/System.IO.Abstractions/pull/211. Could you accept those PR's please?

This is quite blocking for me :-s

**Comment by tathamoddie** [comment]
PR #211 landed.

**Comment by rdehuyss** [comment]
Awesome, thx!
