### ISSUE TITLE
NuGet distribution is built in debug mode

### ISSUE THREAD

**Issue by gunnim** [tathamoddie/System.IO.Abstractions#234]
Is there a reason for this? Seems like it would be better to distribute the package in release mode.

(I checked with a directory scanning fork of https://assemblyinformation.codeplex.com/)

**Comment by tathamoddie** [comment]
Probably just my inability to configure Appveyor more effectively. Could you try a PR for the required changes to `appveyor.yml`?

**Comment by tathamoddie** [comment]
Should be Release mode as of 2.1.0.170
