### ISSUE TITLE
Discuss: Test method names shortening by removing redundant test class name in method

### ISSUE THREAD

**Issue by ericnewton76** [tathamoddie/System.IO.Abstractions#73]
Within the MockDirectoryTests type, do we really need to redundantly name the methods "MockDirectory_GetFiles_ShouldFilterByExtensionBasedSearchPatternAndSearchOptionTopDirectoryOnly" with the name of the type? 

Since this could shorten to:
GetFiles_ShouldFilterByExtensionBasedSearchPatternAndSearchOptionTopDirectoryOnly

I believe all the test runners report a test as
```
TypeName.TestMethod
```
so this illustrates the redundancy:
```
MockDirectoryTests.MockDirectory_GetFiles_ShouldFilterByExtensionBasedSearchPatternAndSearchOptionTopDirectoryOnly
```

Sorry... just a nitpick.

**Comment by tathamoddie** [comment]
I use this convention so that it's easier to read the rules in the VS test explorer. The ReSharper test runner has a better experience, where this isn't required. But really, who's going to bother going back and changing every single one? I'm not intending to.
