### ISSUE TITLE
File.OpenWrite implementation differences between framework 3.5 and 4.0

### ISSUE THREAD

**Issue by ericnewton76** [tathamoddie/System.IO.Abstractions#76]
So FYI, the framework 3.5 implementation of File.OpenWrite will throw FileNotFoundEx if the file doesnt already exist, whereas framework 4.0 implementation will create the file.

Is there any desire to handle framework implementation differences somehow?

**Comment by tathamoddie** [comment]
https://github.com/tathamoddie/System.IO.Abstractions/blob/95d5965c005f06efd6282de57ce891f1d10b814f/TestHelpers.Tests/MockFileTests.cs#L935 demonstrates that we follow the 4.0 convention you've described. As of 94a9fbcbe67c86b187c6d19de36d20482203602d, we're 4.0 only.
