### ISSUE TITLE
File.Copy(string, string, bool) Should Throw DirectoryNotFoundException

### ISSUE THREAD

**Issue by seth-orell-volusion** [tathamoddie/System.IO.Abstractions#95]
There is a discrepancy between the behavior of `System.IO.File.Copy()` and the behavior of `System.IO.Abstractions.TestingHelpers.MockFile.Copy()`. In the .NET library, if any part of the path of its second argument (destFileName) does not exist, it will throw a `DirectoryNotFoundException`. The code in MockFile's `Copy()` leads to an `AddFile()` that will create any missing directories automatically.

I would expect similar exceptions if the destination directory path does not exist in full.

For example, the following code will throw if you set up the source directory with an empty file and do not create the destination directory:
```C#
var filePath = @"C:\PathThatExists\fileName.txt";
File.Copy(filePath, @"C:\PathThatDoesNotExist\fileName.txt", true);
```

**Comment by tathamoddie** [comment]
Fixed in 796018b38bf54c191604cc8b21be02877958893b by @manne
